# Generated by Django 2.2.3 on 2020-10-21 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_name', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Author')),
                ('country', models.CharField(max_length=250, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_name', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Publisher')),
                ('pub_add', models.TextField(verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False, verbose_name='ISBN')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Title')),
                ('pub_year', models.DateField(verbose_name='Publish Year')),
                ('unit_price', models.IntegerField(verbose_name='Unit Price')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Author', verbose_name='Author of book')),
                ('publishers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Publisher', verbose_name='Publisher of book')),
            ],
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
