# Generated by Django 2.2.3 on 2020-10-16 20:54

from django.db import migrations, models
import status.models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20201015_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=status.models.upload_image_path_function),
        ),
    ]
